### ISSUE TITLE
Search with advanced search params

### ISSUE THREAD

**Issue by harlessmark** [vitorgalvao/mtg-card-search-workflow#1]
I would love to see an option for using [Scryfall's advanced search](https://scryfall.com/advanced)! So, for instance, if I wanted to find all Esper commanders with the word "artifact" in their oracle text, I would search:

`colors=wub is:commander o:artifact`

That search would look like this:

https://scryfall.com/search?q=colors%3Dwub+is%3Acommander+o%3Aartifact&unique=cards&as=grid&order=name

**Comment by vitorgalvao** [comment]
Are you asking for a way to give those parameters in Alfred and:

* Press <kbd>⏎</kbd> and the search opens in the browser?
* Matches show up in Alfred like a regular `mtg` search in the workflow?

The first one is quite doable with a [Keyword](https://www.alfredapp.com/help/workflows/inputs/keyword/) and [Open URL](https://www.alfredapp.com/help/workflows/actions/open-url/). The latter is likely to still be possible, but it requires accessing their API which has a noticeable delay. That’s how the workflow worked initially, but currently it downloads and transforms their [bulk data files](https://scryfall.com/docs/api/bulk-data) which is easier on their servers and faster in the workflow.

**Comment by harlessmark** [comment]
The first one sounds better. I didn't know you could do that with Alfred. Cheers!
